version: '0.0.1.{build}'
branches:
  only:
    - master

image: Visual Studio 2015
clone_depth: 1
environment:
  global:
    LatestLTSQtVersion: 5.9
  matrix:
  - QT5: C:\Qt\%LatestLTSQtVersion%\mingw53_32
    COMPILER: C:\Qt\Tools\mingw530_32
    platform: x86
    use_mingw: "true"
  - QT5: C:\Qt\%LatestLTSQtVersion%\msvc2015_64
    COMPILER: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
    platform: amd64

matrix:
  fast_finish: true

before_build:
- set PATH=%COMPILER%\bin;%QT5%\bin;%PATH%
- if not %use_mingw%==true call "%COMPILER%\vcvarsall.bat" %platform%
- if %use_mingw%==true (set MAKEGENERATOR=mingw32-make) else (set CMAKEGENERATOR=nmake)
- if %use_mingw%==true set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

build_script:
- qmake
- %MAKEGENERATOR% debug
- %MAKEGENERATOR% release